### ISSUE TITLE
Populate LS - Client Info – Age (eOZJ5fonziS) with the LS - Client Info - Date of Birth (BvsJfkddTgZ).

### ISSUE THREAD

**Issue by nancyespinoza** [psi-mis/lesotho#2]
_CT: "I'd like to let you know that we have data element called "Age" (e4XZKCNJjlc) which is used in "NewTest" and has the same way of caluating value.So please make sure that we need this attribute OR we can use the exiting data element (e4XZKCNJjlc) instead ??"_

**R/** As far as I know, that DE is calculated using DoB against the event date, so it will not be updated if years go by. I think is better to use the new ATT.
> Age = AgeBetween([Current date],[Date of Birth])

**Comment by chauthutran** [comment]
**_R/ As far as I know, that DE is calculated using DoB against the event date, so it will not be updated if years go by. I think is better to use the new ATT._**

For the data element "Age", we calculated based on the date "HIV Test" event is created ( EventDate is created by using currentDate ). And this value cannot be changed.

For the trackedentity attribute age, as you need, we calculate from currentDate ( "current date" is the date we create relationship ). After that, this value cannot be changed either.
For **creating new client for relationship**, do we need to convert this "age" to "Date of Birth" and saved for client ?. Also for this "Age" value, we still need to save in database, even this value is fixed value ( fixed value means "1 year later, 2 year later, .. the client has the same "age" ) ? I think we don't need this data value because we have "Date of Birth" ( dynamic value ).

So I suggested that we can implement "AGE" value type for attribute so that we can use "Date of birth" in the "Add Relationship" form. We don't need to implement this value type so complicated like DHIS, we can implement an input field so that user enter an integer. When we save data,  we will convert this integer value to date. How do you think ?

**Comment by nancyespinoza** [comment]
Yes! That solution works perfect. Lets do that. Thank you.
