### ISSUE TITLE
DataElement "HIV Status",

### ISSUE THREAD

**Issue by nancyespinoza** [psi-mis/lesotho#5]
1. In "New" case, this field is hidden. It means in "Indexing" tab, we will not see any data in last column "HIV Status"

2. In "Update" case, this field is disabled and mandatory. But no any logic to generate data for this field. So, we cannot create relationship because the validation will check and error in this field.

**Comment by nancyespinoza** [comment]
Not sure if I get the question correctly but the HIV Status for existing clients:
1. In the relationship form: show the value of the HIV Status (not editable)
2. Actions:
- If HIV Status = Positive: create the relationship

- If HIV <> Positive: create the relationship and  create the contact log event

**Comment by chauthutran** [comment]
Hi Nancy,

@From Nancy : **_1. In the relationship form: show the value of the HIV Status (not editable)_**
"HIV Status" is mandatory field.
The value of this case may be empty in case the client was created by using "Add Relationship" form.
 In case the value of this field is empty, we cannot create new relationship.
So I suggested that If this field value is empty, we should let user edit value.
How do you think ?

Another issue is when we add new a client for relationship , then HIV field is hidden. So after creating relationship, we can see this new relationship in "Indexing" tab, but value of "HIV Status" column is empty.
I am not sure if we should leave "HIV Status" is empty or we can fill up some data there, such as value of "HIV Status reported by the index lead" ???

**Comment by rodmelia** [comment]
It's ok to have the value of HIV status empty if the related client doesn't have a test done yet. Leave it empty - we can only display the HIV status if the client has a test.

If during an index search you get a client that doesn't have a test yet, just display "no testing data yet" on the indexing form

Priority: med

**Comment by nancyespinoza** [comment]
This is great:
![image](https://user-images.githubusercontent.com/44774809/91494499-2a332000-e876-11ea-8f28-451558f5620c.png)

But in the relationship form I still see the HIV Status with the possibility to be filled by the user. This is supposed to be filled only if the client has already been tested. Not sure if we can add the same label "no testing data yet" to the field or if it is better to hide it. Please advice. 
![image](https://user-images.githubusercontent.com/44774809/91494709-8138f500-e876-11ea-8fe1-7c28efc50d8d.png)

**Comment by chauthutran** [comment]
In "Add Relationship" form, "HIV Status" is mandatory field and disabled. Because of this logic, for all clients without any test, we cannot create any relationship because of "HIV Status" is empty ( your case is an example ).
That's the reason why **I enabled this field** so that we can fill up data in this field and create relationship.

We hide this field in "Add New" client for relationship. For the existing client, we show it and it is mandatory + disabled.

So, I'd like to suggest that we shouldn't make this field is mandatory. How do you think ?

**Comment by nancyespinoza** [comment]
We will have a call with Lesotho team on Monday. So I'll let you know the workaround then. Thank you

**Comment by chauthutran** [comment]
Is there any news for this one ?

**Comment by nancyespinoza** [comment]
Hi Tran! Monday call was cancelled. We are having it tomorrow (Wednesday). I'll let you know then. Thank you

**Comment by Leahbartlett** [comment]
I had a friend who died of Hiv back in 2000 and ever since then, I have always be interested in learning about the virus. He looked healthy, he seemed fine and then one day he invited me to a christmas dinner and when I went, I was surrounded by people with Hiv and he disclose it to me and it blew my friggen mind.... I was scared, not sure how to deal with it... and then about three years after that he passed away. I did some research and listened to people stories and testimony about Dr. kanayo 14 days herbal medicine. I most confess I was so impressed with the news. then I met a female friend that has the virus too, she wasn’t taking her meds and she has had it since the year 2000 I told her about the Dr. kanayo and shared the WhatsApp +1(909) 375-5642 with her, she got and use it as Dr kanayo told her. she’s no longer positive everyone needs to know this great news. I wish my friend was still alive to use this great herbal product but I know God knows best. ****

**Comment by nancyespinoza** [comment]
Hi Tran, 
After the call, we conclude using this DE as follows:

- Indexing: Creating a new client
**As you already have configured**, we do not have to show the HIV Status DE.

- Indexing: Adding an existing client

1. If last HIV Status is positive
Display the value non-editable. Create the relationship but do not create the contact log event. 
Hide:
- LS HTS TRK - Background - HIV Status (bCVRuaX7LwG) 
- LS HTS TRK - Background - Notification Method (Eis9qerhBFg) 
- LS HTS TRK - ContactLog - Due Date (HcBFZsCt8Sy) 

2. If last HIV Status is different from positive
Display the value non-editable. Create the relationship and the contact log event.
Show: 
- LS HTS TRK - Background - HIV Status (bCVRuaX7LwG) 
- LS HTS TRK - Background - Notification Method (Eis9qerhBFg) 
- LS HTS TRK - ContactLog - Due Date (HcBFZsCt8Sy) 

3. If last HIV Status is empty (no value)
Create the relationship and the contact log event.
Hide LS HTS TRK - Test - Final HIV status (UuKat0HFjWS) 
Show:
- LS HTS TRK - Background - HIV Status (bCVRuaX7LwG) 
- LS HTS TRK - Background - Notification Method (Eis9qerhBFg) 
- LS HTS TRK - ContactLog - Due Date (HcBFZsCt8Sy) 


Please let me know any questions

**Comment by chauthutran** [comment]
Hi Nancy,

_@From Nancy:  we conclude using this DE as follows:_

Indexing: Creating a new client
As you already have configured, we do not have to show the HIV Status DE.
**--> It means we should leave this column as Empty OR we should show  display "no testing data yet" ?**

**Comment by chauthutran** [comment]
I found the answer in #13

**Comment by nancyespinoza** [comment]
Hi Tran! in the case 3.
_If last HIV Status is empty (no value)
Create the relationship and the contact log event.
Hide LS HTS TRK - Test - Final HIV status (UuKat0HFjWS)
Show:
LS HTS TRK - Background - HIV Status (bCVRuaX7LwG)
LS HTS TRK - Background - Notification Method (Eis9qerhBFg)
LS HTS TRK - ContactLog - Due Date (HcBFZsCt8Sy)_

I'm having two different behaviors (not expected):
1. The app does not allow me to link
![20200909103319](https://user-images.githubusercontent.com/44774809/92626942-e550b580-f287-11ea-8c88-dc35b4febd72.gif)

2. The app allows to link but it still shows the HIV Status field.
![20200909103351](https://user-images.githubusercontent.com/44774809/92626997-fa2d4900-f287-11ea-96af-c39eeaef9664.gif)

**Comment by chauthutran** [comment]
Hi Nancy,
Can you give me more details what kind of client in issue 1 and issue 2 so that you can simulate the bugs in my side ?

**Comment by nancyespinoza** [comment]
Hi Tran!
Looks like in some cases, the HIV status does not show in the relationship form, even when it has a previous value. (Example: Gary Smith)

![20200911103336](https://user-images.githubusercontent.com/44774809/92950645-43150700-f41a-11ea-82cc-a311c7d2f4fd.gif)
